application:
  name: node-sum
  project: node-microservices
  cloud_region: aws/eu-west-3
  publicly_accessible: true
routers:
  - name: main
    routes:
      - application_name: node-sum
        paths:
          - /*
